// 此文件由 src-tauri 自动生成（tauri-specta），请勿手动修改。

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	listProjects: () => __TAURI_INVOKE<ProjectSummary[]>("list_projects"),
	/**  弹出系统的“选择文件夹”对话框。用户取消时返回 null。 */
	pickFolder: () => __TAURI_INVOKE<{
	/**  一次性令牌，加入项目时交回。 */
	token: string,
	/**  仅用于显示。 */
	path: string,
} | null>("pick_folder"),
	checkAddProject: (token: string) => __TAURI_INVOKE<AddCheck>("check_add_project", { token }),
	/**  加入项目。`associate_previous` 为用户选择关联的原历史项目 ID。 */
	addProject: (token: string, associatePrevious: string | null) => __TAURI_INVOKE<ProjectSummary>("add_project", { token, associatePrevious }),
	removeProject: (projectId: string) => __TAURI_INVOKE<null>("remove_project", { projectId }),
	openProject: (projectId: string) => __TAURI_INVOKE<ProjectOverview>("open_project", { projectId }),
	projectOverview: (projectId: string) => __TAURI_INVOKE<ProjectOverview>("project_overview", { projectId }),
	/**  在系统文件管理器中打开项目文件夹。 */
	revealProjectFolder: (projectId: string) => __TAURI_INVOKE<null>("reveal_project_folder", { projectId }),
	currentChanges: (projectId: string, taskId: string, onProgress: Channel<ProgressEvent>) => __TAURI_INVOKE<ChangeSet>("current_changes", { projectId, taskId, onProgress }),
	saveVersion: (request: SaveRequest, taskId: string, onProgress: Channel<ProgressEvent>) => __TAURI_INVOKE<SaveResult>("save_version", { request, taskId, onProgress }),
	/**  请求取消长任务。任务会在处理完当前文件后停止。 */
	cancelTask: (taskId: string) => __TAURI_INVOKE<boolean>("cancel_task", { taskId }),
	exclusionRules: (projectId: string) => __TAURI_INVOKE<RuleView[]>("exclusion_rules", { projectId }),
	countRuleMatches: (projectId: string, rules: ExclusionRule[]) => __TAURI_INVOKE<number[]>("count_rule_matches", { projectId, rules }),
	saveExclusionRules: (projectId: string, rules: ExclusionRule[]) => __TAURI_INVOKE<null>("save_exclusion_rules", { projectId, rules }),
	listWorkspaceDir: (projectId: string, dir: string | null) => __TAURI_INVOKE<DirChild[]>("list_workspace_dir", { projectId, dir }),
	timeMap: (projectId: string) => __TAURI_INVOKE<TimeMap>("time_map", { projectId }),
	/**  版本或安全备份中的全部文件与文件夹。 */
	sourceFiles: (projectId: string, source: SourceRef) => __TAURI_INVOKE<HistoryEntry[]>("source_files", { projectId, source }),
	previewFile: (projectId: string, source: SourceRef, path: string) => __TAURI_INVOKE<FilePreview>("preview_file", { projectId, source, path }),
	compareVersions: (projectId: string, versionA: string, versionB: string, scope: string | null) => __TAURI_INVOKE<CompareResult>("compare_versions", { projectId, versionA, versionB, scope }),
	diffFile: (projectId: string, versionA: string, versionB: string, path: string) => __TAURI_INVOKE<FileDiff>("diff_file", { projectId, versionA, versionB, path }),
};

/** Events */
export const events = {
	folderDropped: makeEvent<FolderDropped>("folder-dropped"),
};

/* Types */
/**  加入前的检查结果。 */
export type AddCheck = {
	path: string,
	name: string,
	/**  该路径曾作为项目被移除：由用户选择关联原历史或作为新项目（不自动关联）。 */
	previous: PreviousProject | null,
};

export type AppInfo = {
	version: string,
	/**  历史存储目录（界面在“存储管理”中显示）。 */
	data_dir: string,
	/**  windows / macos / linux */
	os: string,
};

export type ChangeCounts = {
	/**  新增、修改、删除的文件数（不含文件夹）。 */
	added: number,
	modified: number,
	deleted: number,
	dirs_added: number,
	dirs_deleted: number,
	excluded_now: number,
};

export type ChangeItem = {
	path: string,
	kind: ChangeKind,
	/**  当前的类型；已删除或不再纳入时为基准中的类型。 */
	entry_type: EntryType,
	/**  文件大小（字节）；文件夹为 null。 */
	size: number | null,
};

export type ChangeKind = "added" | "modified" | "deleted" | 
/**  同一路径在文件与文件夹之间变化。 */
"type_changed" | 
/**  基准中有、但按当前排除规则不再纳入（不计为删除）。 */
"excluded_now";

export type ChangeSet = {
	/**  比较基准；尚无版本时为 null，此时全部文件显示为新增。 */
	baseline_version_id: string | null,
	items: ChangeItem[],
	counts: ChangeCounts,
	/**  排除规则相对基准版本保存时发生了变化。 */
	rules_changed: boolean,
	/**  需要用户处理的条目（链接、云占位、无法读取等）；存在时不能保存。 */
	problems: ScanProblem[],
	file_count: number,
	directory_count: number,
	/**  有可保存的变化（尚无版本时总为 true，允许保存空文件夹）。 */
	has_changes: boolean,
};

export type CompareCounts = {
	added: number,
	deleted: number,
	modified: number,
	type_changed: number,
	excluded_in_b: number,
};

export type CompareItem = {
	path: string,
	kind: CompareKind,
	/**  B 中的类型；B 中没有时为 A 中的类型。 */
	entry_type: EntryType,
	size_a: number | null,
	size_b: number | null,
};

export type CompareKind = "added" | "deleted" | "modified" | "type_changed" | 
/**  A 中有、B 中没有，且该路径在 B 保存时被排除（不计为删除）。 */
"excluded_in_b";

export type CompareResult = {
	a: VersionBrief,
	b: VersionBrief,
	/**  只比较了这个文件夹（null 表示整个项目）。 */
	scope: string | null,
	items: CompareItem[],
	counts: CompareCounts,
};

export type CoreError = {
	code: ErrorCode,
	/**  面向用户的中文说明。 */
	message: string,
	/**  涉及的路径（如有）。日志只记录错误码和路径，不记录文件正文（LFVM-Q-08）。 */
	path: string | null,
};

export type DiffLine = {
	tag: LineTag,
	/**  A 中的行号（从 1 开始）。 */
	old_no: number | null,
	/**  B 中的行号（从 1 开始）。 */
	new_no: number | null,
	text: string,
};

/**  项目目录树中的一个子项（用于在界面中选择要排除的文件或文件夹）。 */
export type DirChild = {
	path: string,
	name: string,
	is_dir: boolean,
	/**  按已保存的规则是否被排除。 */
	excluded: boolean,
};

/**  版本清单、备份清单中的条目类型。 */
export type EntryType = "file" | "directory";

/**  错误码。新增时只在末尾追加，界面文案在前端按错误码维护。 */
export type ErrorCode = 
/**  输入不符合格式（名称长度、必填项等）。 */
"INVALID_INPUT" | 
/**  路径为空、为绝对路径、含“..”或无法解析。 */
"INVALID_PATH" | 
/**  路径超出项目、历史存储或用户选择的范围。 */
"PATH_OUT_OF_SCOPE" | 
/**  路径超出系统支持的长度。 */
"PATH_TOO_LONG" | 
/**  遇到未排除的链接对象（符号链接、目录联接）。 */
"LINK_NOT_FOLLOWED" | 
/**  仅存于云端的占位文件。 */
"CLOUD_PLACEHOLDER" | 
/**  磁盘根目录或系统目录。 */
"PROTECTED_DIRECTORY" | 
/**  与已登记项目或历史存储目录相同或相互包含。 */
"DIRECTORY_OVERLAP" | "NOT_FOUND" | "ALREADY_EXISTS" | "PERMISSION_DENIED" | 
/**  文件被其他程序占用。 */
"FILE_IN_USE" | 
/**  磁盘空间不足。 */
"NO_SPACE" | 
/**  文件在操作过程中被外部修改。 */
"CHANGED_EXTERNALLY" | 
/**  同一项目已有写操作在进行。 */
"BUSY" | "CANCELLED" | 
/**  项目存在未处置的未完成操作（SRS 6.1.1）。 */
"INCOMPLETE_OPERATION" | 
/**  历史内容校验失败。 */
"CONTENT_CORRUPTED" | "DATABASE" | "IO" | "INTERNAL" | 
/**  没有需要保存的变化。 */
"NOTHING_TO_SAVE" | 
/**  版本或安全备份的内容已清理。 */
"CONTENT_CLEARED";

export type ExclusionRule = {
	relative_path: string,
	entry_type: RuleType,
	is_system_default: boolean,
	enabled: boolean,
};

export type FileDiff = { kind: "text"; lines: DiffLine[]; encoding_a: string | null; encoding_b: string | null; 
/**  换行符或文件末尾换行的差异说明。 */
notes: string[] } | 
/**  一侧不存在时为 null。 */
{ kind: "image"; a: ImageSide | null; b: ImageSide | null } | 
/**  只显示文件级状态，并说明原因。 */
{ kind: "unsupported"; reason: string };

export type FilePreview = {
	path: string,
	size: number,
	hash: string,
	content: PreviewContent,
};

/**  用户把文件或文件夹拖入窗口。拖入的不是文件夹时 `folder` 为 null。 */
export type FolderDropped = {
	folder: PickedFolder | null,
};

/**  历史版本中的一个文件或文件夹。 */
export type HistoryEntry = {
	path: string,
	entry_type: EntryType,
	size: number | null,
	hash: string | null,
	/**  内容对象缺失时为 false（显示“内容损坏”）。 */
	available: boolean,
};

export type ImageFormat = "png" | "jpeg";

export type ImageInfo = {
	format: ImageFormat,
	width: number,
	height: number,
};

/**  图片比较中的一侧。 */
export type ImageSide = {
	hash: string,
	/**  可显示时给出尺寸；不可显示时为 null，并给出原因。 */
	info: ImageInfo | null,
	reason: string | null,
};

export type LineTag = "equal" | "insert" | "delete";

/**  时间地图中的一个版本节点。 */
export type MapNode = {
	version_id: string,
	seq: number,
	parent_version_id: string | null,
	/**  保存时所在的方案；null 表示在默认历史中保存。 */
	origin_scheme_id: string | null,
	/**  保存时所在方案的名称（方案已清理时仍保留，供显示）。 */
	origin_scheme_name: string | null,
	name: string,
	note: string,
	created_at: number,
	file_count: number,
	directory_count: number,
	added: number,
	modified: number,
	deleted: number,
	/**  内容已清理（占位节点）：不能浏览、比较或恢复。 */
	cleared: boolean,
};

export type MapScheme = {
	scheme_id: string,
	name: string,
	base_version_id: string,
	head_version_id: string,
	created_at: number,
	/**  已清理的方案不在方案列表中显示，但其版本仍按原方案着色。 */
	cleared: boolean,
};

/**  用户通过对话框或拖放选中的文件夹。 */
export type PickedFolder = {
	/**  一次性令牌，加入项目时交回。 */
	token: string,
	/**  仅用于显示。 */
	path: string,
};

export type PreviewContent = { kind: "text"; text: string; encoding: string } | 
/**  图片经预览协议加载：`lfvm-preview://localhost/<project_id>/<hash>` */
{ kind: "image"; hash: string; info: ImageInfo } | 
/**  不显示内容，给出原因。 */
{ kind: "unsupported"; reason: string };

export type PreviousProject = {
	project_id: string,
	name: string,
	version_count: number,
	created_at: number,
};

export type ProgressEvent = {
	stage: Stage,
	/**  已完成量（文件数或字节数，视阶段而定）；total 为 0 表示总量未知。 */
	done: number,
	total: number,
};

/**  打开项目后的概览（表 8-3“项目概览”）。 */
export type ProjectOverview = {
	project: ProjectSummary,
	/**  当前活动方案；null 表示处于默认历史。 */
	active_scheme: SchemeBrief | null,
	/**  当前比较基准（规则 R-01）；尚无版本时为 null。 */
	baseline: VersionBrief | null,
	version_count: number,
};

/**  项目列表中的一项。 */
export type ProjectSummary = {
	project_id: string,
	name: string,
	root_path: string,
	/**  UTC 毫秒。 */
	created_at: number,
	/**  存在未处置的未完成操作（SRS 6.1.1）。 */
	incomplete: boolean,
	/**  工作文件夹当前是否仍可访问；不可访问时只能移除。 */
	accessible: boolean,
};

export type RuleType = "file" | "directory" | 
/**  文件名模式，仅用于系统默认规则。 */
"name_pattern";

/**  排除项设置界面中的一条规则。 */
export type RuleView = {
	rule: ExclusionRule,
	/**  当前匹配到的文件数。 */
	match_count: number,
};

export type SaveRequest = {
	project_id: string,
	/**  界面为每次“确认保存”生成的标识；重复提交同一请求不会重复保存（LFVM-Q-05）。 */
	request_id: string,
	name: string,
	note: string,
};

export type SaveResult = {
	version_id: string,
	seq: number,
	added: number,
	modified: number,
	deleted: number,
	file_count: number,
	directory_count: number,
};

/**  扫描时遇到、需要用户处理的条目。 */
export type ScanProblem = {
	path: string,
	code: ErrorCode,
	message: string,
};

export type SchemeBrief = {
	scheme_id: string,
	name: string,
};

/**  历史文件的来源：某个版本或某个安全备份。 */
export type SourceRef = { kind: "version"; version_id: string } | { kind: "backup"; backup_id: string };

/**  任务所处阶段，界面据此显示“正在扫描”“正在保存文件”等。 */
export type Stage = 
/**  列出文件夹内容 */
"listing" | 
/**  计算内容摘要 */
"hashing" | 
/**  写入历史存储 */
"storing" | 
/**  再次核对工作区 */
"verifying" | 
/**  登记到数据库 */
"committing";

export type TimeMap = {
	/**  按保存先后（序号）排列。 */
	nodes: MapNode[],
	/**  全部方案（含已清理），按创建先后排列。 */
	schemes: MapScheme[],
	default_head: string | null,
	active_scheme_id: string | null,
};

export type VersionBrief = {
	version_id: string,
	/**  项目内序号，界面显示为 “V{seq}”。 */
	seq: number,
	name: string,
	note: string,
	created_at: number,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

